name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: calculator-app
          path: target/MinimalCalculator.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: calculator-app

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          scp -i $EC2_KEY MinimalCalculator.war $EC2_USER@$EC2_HOST:/home/ubuntu/
          ssh -i $EC2_KEY $EC2_USER@$EC2_HOST <<EOF
          sudo mv /home/ubuntu/MinimalCalculator.war /var/lib/tomcat/webapps/
          sudo systemctl restart tomcat
          EOF
