name: Java Build with CodeQL and WAR Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 (ensure that it's available on GitHub Actions runner)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Generate the WAR file and place it in the target directory
      - name: Build WAR file
        run: |
          mvn clean package

      # Upload the generated WAR file as an artifact (optional, for later download)
      - name: Upload WAR file
        uses: actions/upload-artifact@v2
        with:
          name: calculator-app-war
          path: target/*.war

      # Set up CodeQL for Java
      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Perform CodeQL analysis
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
