name: Java CI with Maven

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step 3: Cache Maven dependencies to speed up builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the project using Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Upload the .war file as a build artifact
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-servlet-calculator
        path: target/*.war
