name: Java CI CD pipeline with Maven Tomcat

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-servlet-calculator
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures CI runs first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact from CI Build
        uses: actions/download-artifact@v4
        with:
          name: java-servlet-calculator
          path: target/

      - name: Verify Artifact Exists
        run: ls -l target/

      - name: Add SSH Key to Agent
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

      - name: Copy WAR to Bastion Host
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem target/*.war ubuntu@${{ secrets.BASTION_PUBLIC_IP }}:/home/ubuntu/

      - name: SSH into Bastion & Transfer WAR to Private Instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_PUBLIC_IP }} << 'EOF'
            scp -o StrictHostKeyChecking=no /home/ubuntu/*.war ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }}:/opt/tomcat/webapps/
          EOF

      - name: Restart Tomcat on Private Instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.BASTION_PUBLIC_IP }} << 'EOF'
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }} "
              sudo systemctl restart tomcat
            "
          EOF
