name: Java CI CD pipeline with Maven Tomcat

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-servlet-calculator
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure CI runs first

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact from CI Build
        uses: actions/download-artifact@v4
        with:
          name: java-servlet-calculator
          path: target/

      - name: Verify Artifact Exists
        run: ls -l target/

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Disable strict host checking and known hosts
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" > ~/.ssh/config

      # ✅ Use SSH Agent Forwarding Instead of Copying Keys
      - name: Add SSH Key to Agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-add -l  # Debugging to check if the key is loaded

      # ✅ SCP Directly to Private Instance via Bastion using `-J`
      - name: Copy WAR to Private Instance (via Bastion)
        run: |
          scp -o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${{ secrets.BASTION_PUBLIC_IP }} \
          target/*.war ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }}:/home/ubuntu/

      # ✅ Deploy WAR to Tomcat using Bastion as Proxy (`-J`)
      - name: Move WAR to Tomcat Webapps
        run: |
          ssh -o StrictHostKeyChecking=no -J ubuntu@${{ secrets.BASTION_PUBLIC_IP }} ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }} << 'EOF'
            sudo mv /home/ubuntu/*.war /var/lib/tomcat9/webapps/
            sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/*.war
            sudo chmod 644 /var/lib/tomcat9/webapps/*.war
          EOF

      # ✅ Restart Tomcat on Private Instance via Bastion (`-J`)
      - name: Restart Tomcat Service
        run: |
          ssh -o StrictHostKeyChecking=no -J ubuntu@${{ secrets.BASTION_PUBLIC_IP }} ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }} \
          "sudo systemctl restart tomcat9"
