name: Deploy to Tomcat

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download WAR Artifact from CI Build
        uses: actions/download-artifact@v4
        with:
          name: java-servlet-calculator
          path: target/

      - name: Set Permissions for SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy WAR to Bastion Host
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem target/*.war ubuntu@${{ secrets.BASTION_PUBLIC_IP }}:/home/ubuntu/
      
      - name: SSH into Bastion & Transfer WAR to Private Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BASTION_PUBLIC_IP }} << 'EOF'
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa /home/ubuntu/*.war ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }}:/opt/tomcat/webapps/
          EOF

      - name: Restart Tomcat on Private Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.BASTION_PUBLIC_IP }} << 'EOF'
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_INSTANCE_IP }} "
              sudo /opt/tomcat/bin/shutdown.sh && sleep 5 && sudo /opt/tomcat/bin/startup.sh
            "
          EOF

      - name: Cleanup Private Key
        run: rm -f private_key.pem
